"""empty message

Revision ID: 5b8c8adf7b34
Revises: 7e75adde12c5
Create Date: 2019-12-11 15:46:49.426146

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5b8c8adf7b34'
down_revision = '7e75adde12c5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('address', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('events', 'address')
    # ### end Alembic commands ###
