"""empty message

Revision ID: 7e75adde12c5
Revises: e7c5db70fea6
Create Date: 2019-12-11 15:46:29.850492

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7e75adde12c5'
down_revision = 'e7c5db70fea6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('events', 'address')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('address', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
