"""empty message

Revision ID: e338a0a462a7
Revises: 95abdd3f3e37
Create Date: 2019-12-02 12:23:44.727885

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e338a0a462a7'
down_revision = '95abdd3f3e37'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('email', sa.String(), nullable=False))
    op.alter_column('user', 'name',
               existing_type=sa.VARCHAR(length=256),
               nullable=False)
    op.drop_constraint('user_name_key', 'user', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('user_name_key', 'user', ['name'])
    op.alter_column('user', 'name',
               existing_type=sa.VARCHAR(length=256),
               nullable=True)
    op.drop_column('user', 'email')
    # ### end Alembic commands ###
